# -*- coding: utf-8 -*-
"""Final Exam Review

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1en2M6rvRCdql8Hx4C0RrTv1q3Hhm7KYr
"""

#Lucas Vandenakker
#CS175
#Q1

date_string = '11/26/2020'

str_split = date_string.split("/")

month = str_split[0]
day = str_split[1]
year = str_split[2]

print("Month:", month, "\nDay:", day, "\nYear:", year)

#Lucas Vandenakker
#CS175
#Q2

a = [1,2,0,1]
b = [3,4,6,5]
total =0

for x in a:
  if x == 0:
    continue
  total += x * b[a.index(x)]

print(total)

#Lucas Vandenakker
#CS175
#Q3

sentence = "apple banana apple orange banana apple"

words = sentence.split(" ")

num_words = {}

for word in words:
  if word not in num_words:
    num_words[word] = 1
  else:
    num_words[word] += 1

print(num_words)

#Lucas Vandenakker
#CS175
#Q4

text = "Hello, World!"
vowels = "aeiouAEIOU"
count = 0

for char in text:
  if char in vowels:
    text = text.replace(char, "@")

print(text)

#Lucas Vandenakker
#CS175
#Q5

sentence = "its raining cats and dogs"

words = sentence.split(" ")

sentence = " ".join([word.capitalize() for word in words])

print(sentence)

#Lucas Vandenakker
#CS175
#Q6

sentence = "Chicago is very different from Boston"

words = sentence.split()


longest = words[0]
for word in words:
  if len(word) > len(longest):
    longest = word

print("The longest word is " + longest)

#Lucas Vandenakker
#CS175
#Q7

text = "Python 3.9 is great for 2024!"

newText = "".join(char for char in text if not char.isdigit())

print(newText)

#Lucas Vandenakker
#CS175
#Q8

text = "Hello World! Python3"

lower = 0
upper = 0
digits = 0

for letter in text:
  if not letter.isdigit() and letter.isalnum():
    if letter.islower():
      lower+=1
    else:
      upper+=1

  elif(letter.isalnum()):
    digits+=1

uppercase = sum(1 for char in text if char.isupper())
lowercase = sum(1 for char in text if char.islower())
digits2 = sum(1 for char in text if char.isdigit())

print("Lower characters:", lowercase)
print("Upper characters:", uppercase)
print("Digits:", digits2)

#Lucas Vandenakker
#CS175
#Q9

str1 = "listen"
str2 = "silent"

str1new = "".join(sorted(str1))
str2new = "".join(sorted(str2))

if str1new == str2new:
  print("Yes, they are anagrams")
else:
  print("No, they are not anagrams")

#Lucas Vandenakker
#CS175
#Q10

# Initial inventory
inventory = {
    "apple": 10,
    "banana": 5,
    "orange": 8
}

# List of items sold
sold_items = ["apple", "banana", "grape", "apple", "orange", "banana"]

for item in sold_items:
  if item in inventory:
    print(f"Sold an {item}")
    inventory[item] -=1

print("\nUpdated inventory:")
for item, quantity in inventory.items():
    print(f"{item}: {quantity}")

